# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
if GetDepend('RT_USING_CALIBRATION'):
    src = Glob('*.c')

group = DefineGroup('RTGUI', src, depend = ['RT_USING_CALIBRATION'])

Return('group')
